/*
 * generated by Xtext 2.10.0
 */
package cz.lzaruba.modelx.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ModelXAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("cz/lzaruba/modelx/parser/antlr/internal/InternalModelX.tokens");
	}
}
