/*
 * generated by Xtext 2.10.0
 */
package cz.lzaruba.modelx


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ModelXRuntimeModule extends AbstractModelXRuntimeModule {
}
