/*
 * generated by Xtext 2.10.0
 */
package cz.lzaruba.modelx


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ModelXStandaloneSetup extends ModelXStandaloneSetupGenerated {

	def static void doSetup() {
		new ModelXStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
