/**
 * generated by Xtext 2.10.0
 */
package cz.lzaruba.modelx.modelX;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interface</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cz.lzaruba.modelx.modelX.Interface#getName <em>Name</em>}</li>
 *   <li>{@link cz.lzaruba.modelx.modelX.Interface#getSupertypes <em>Supertypes</em>}</li>
 *   <li>{@link cz.lzaruba.modelx.modelX.Interface#getFeatures <em>Features</em>}</li>
 * </ul>
 *
 * @see cz.lzaruba.modelx.modelX.ModelXPackage#getInterface()
 * @model
 * @generated
 */
public interface Interface extends AbstractElement, FeatureType
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see cz.lzaruba.modelx.modelX.ModelXPackage#getInterface_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link cz.lzaruba.modelx.modelX.Interface#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Supertypes</b></em>' reference list.
   * The list contents are of type {@link cz.lzaruba.modelx.modelX.Interface}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Supertypes</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Supertypes</em>' reference list.
   * @see cz.lzaruba.modelx.modelX.ModelXPackage#getInterface_Supertypes()
   * @model
   * @generated
   */
  EList<Interface> getSupertypes();

  /**
   * Returns the value of the '<em><b>Features</b></em>' containment reference list.
   * The list contents are of type {@link cz.lzaruba.modelx.modelX.Feature}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Features</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Features</em>' containment reference list.
   * @see cz.lzaruba.modelx.modelX.ModelXPackage#getInterface_Features()
   * @model containment="true"
   * @generated
   */
  EList<Feature> getFeatures();

} // Interface
