/*
 * generated by Xtext 2.10.0
 */
package cz.lzaruba.modelx.ui.tests;

import com.google.inject.Injector;
import cz.lzaruba.modelx.ui.internal.ModelxActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class ModelXUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ModelxActivator.getInstance().getInjector("cz.lzaruba.modelx.ModelX");
	}

}
