/*
 * generated by Xtext 2.10.0
 */
package cz.lzaruba.modelx.scoping;

import org.eclipse.xtext.xbase.annotations.typesystem.XbaseWithAnnotationsBatchScopeProvider;

public abstract class AbstractModelXScopeProvider extends XbaseWithAnnotationsBatchScopeProvider {
}
