/*
 * generated by Xtext 2.10.0
 */
package cz.lzaruba.modelx.ui;

import com.google.inject.Injector;
import cz.lzaruba.modelx.ui.internal.ModelxActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ModelXExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ModelxActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ModelxActivator.getInstance().getInjector(ModelxActivator.CZ_LZARUBA_MODELX_MODELX);
	}
	
}
